config/routes.rb
DreamTrends::Application.routes.draw do
  devise_for :users
  resources :dreams
  resources :trends

  root to: "home#index"
end

app/models/dream.rb
class Dream < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :trends

  after_create :add_to_trends
  attr_accessible :title, :body, :dream_date

  def self.trends_between_dates(start_date, end_date=Time.now.beginning_of_day)
    dreams = Dream.dreams_in_range(start_date, end_date)
    return [] if dreams.empty?

    all_trends = dreams.map { |d| d.trends }.flatten.compact
    trend_hash = Hash.new(0)
    all_trends.each do |trend|
      trend_hash[trend] += 1
    end
    trend_hash.sort_by { |k,v| v }.reverse
  end

  def self.dreams_in_range(start_date, end_date)
    Dream.where("dream_date >= ? AND dream_date <= ?", start_date, end_date)
  end

  def add_to_trends
    all_words = body.split(/\W+/).map(&:downcase).uniq.each  do |word|
      trend = Trend.find_or_create_by_word(word)
      trend.dreams << self unless trend.excluded?
    end
  end
end

app/models/trend.rb
class Trend < ActiveRecord::Base
  has_and_belongs_to_many :dreams

  validates :word, uniqueness: true

  before_save :remove_from_dreams_if_excluded
  attr_accessible :excluded

  def remove_from_dreams_if_excluded
    if excluded
      self.dreams.delete_all
    end
  end

  def dreams_in_range(start_date, end_date)
    dreams.where("dream_date >= ? AND dream_date <= ?", start_date, end_date)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :dreams
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController

  before_filter :authenticate_user!, :only => [:new, :create, :destroy]

  # GET /dreams
  # GET /dreams.json
  def index
    @dreams = current_user.dreams

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dreams }
    end
  end

  # GET /dreams/1
  # GET /dreams/1.json
  def show
    @dream = Dream.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dream }
    end
  end

  # GET /dreams/new
  # GET /dreams/new.json
  def new
    @dream = Dream.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dream }
    end
  end

  # POST /dreams
  # POST /dreams.json
  def create
    @dream = Dream.new(params[:dream], user: current_user)

    respond_to do |format|
      if @dream.save
        current_user.dreams << @dream
        format.html { redirect_to @dream, notice: 'Dream was successfully created.' }
        format.json { render json: @dream, status: :created, location: @dream }
      else
        format.html { render action: "new" }
        format.json { render json: @dream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dreams/1
  # DELETE /dreams/1.json
  def destroy
    @dream = current_user.dreams.where(id: params[:id]).first
    if @dream.nil?
       render(status: 401, text: "Unauthorized") && return
    end

    @dream.destroy
    respond_to do |format|
      format.html { redirect_to dreams_url }
      format.json { head :no_content }
    end
  end

  def find_dream
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @last_week = Time.now.beginning_of_day - 7.day
    @top_trends = Dream.trends_between_dates(@last_week)
  end
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  # GET /trends
  # GET /trends.json
  def index
    @trends = Trend.order("excluded ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trends }
    end
  end

  # GET /trends/1
  # GET /trends/1.json
  def show
    @trend = Trend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trend }
    end
  end

  # GET /trends/new
  # GET /trends/new.json
  def new
    @trend = Trend.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trend }
    end
  end

  # GET /trends/1/edit
  def edit
    @trend = Trend.find(params[:id])
  end

  # POST /trends
  # POST /trends.json
  def create
    @trend = Trend.new(params[:trend])

    respond_to do |format|
      if @trend.save
        format.html { redirect_to @trend, notice: 'Trend was successfully created.' }
        format.json { render json: @trend, status: :created, location: @trend }
      else
        format.html { render action: "new" }
        format.json { render json: @trend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trends/1
  # PUT /trends/1.json
  def update
    @trend = Trend.find(params[:id])

    respond_to do |format|
      if @trend.update_attributes(params[:trend])
        format.html { redirect_to @trend, notice: 'Trend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trends/1
  # DELETE /trends/1.json
  def destroy
    @trend = Trend.find(params[:id])
    @trend.destroy

    respond_to do |format|
      format.html { redirect_to trends_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/helpers/trends_helper.rb
module TrendsHelper
end

app/views/dreams/_form.html.erb
<%= form_for(@dream) do |f| %>
  <% if @dream.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dream.errors.count, "error") %> prohibited this dream from being saved:</h2>

      <ul>
      <% @dream.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :dream_date %><br />
    <%= f.date_select :dream_date, start_year: 1900 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dreams/index.html.erb
<h1>Listing dreams</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Dream Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dreams.each do |dream| %>
  <tr>
    <td><%= dream.title %></td>
    <td><%= dream.body %></td>
    <td><%= dream.dream_date.strftime("%d %b %y") %></td>
    <td><%= link_to 'Show', dream %></td>
    <td><%= link_to 'Edit', edit_dream_path(dream) %></td>
    <td><%= link_to 'Destroy', dream, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dream', new_dream_path %>

app/views/dreams/new.html.erb
<h1>New dream</h1>

<%= render 'form' %>

<%= link_to 'Back', dreams_path %>

app/views/dreams/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Title:</b>
  <%= @dream.title %>
</p>

<p>
  <b>Body:</b>
  <%= @dream.body %>
</p>

<p>
  <b>Dream Date:</b>
  <%= @dream.dream_date.strftime("%d %b %y") %>
</p>

<%= link_to 'Back', dreams_path %>

app/views/home/index.html.erb
<% if user_signed_in? %>
    <span>Hello, <%= current_user.email %>!</span>
    <%= link_to "Your Dreams", dreams_path %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
<% else %>
    <%= link_to('Log in or Signup', new_user_session_path)  %>
<% end %>

<br/>
<strong>Dreaming Trends</strong>
<span style="font-size:256px">BETA</span>
<span style="font-size:10px">a division of <a href="http://earlyclues.com">early clues llc.</a></span>

<% unless @top_trends.empty? %>
    <h1>Top Trends For The Week</h1>
<% end%>

<ul>
<% @top_trends.each do |trend_array| %>
   <li>
    <% trend = trend_array[0]%>
    <%= trend.word %><br/>
    <% trend.dreams_in_range(@last_week, Time.now.beginning_of_day).each do |dream| %>
        <%= link_to dream.title, dream_path(dream) %>
    <% end %>
   </li>
   <br/>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DreamTrends</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trends/_form.html.erb
<%= form_for(@trend) do |f| %>
  <% if @trend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trend.errors.count, "error") %> prohibited this trend from being saved:</h2>

      <ul>
      <% @trend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br />
    <strong><%= @trend.word %></strong>
  </div>

  <div class="field">
    <%= f.label :excluded %><br />
    <%= f.check_box :excluded %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trends/edit.html.erb
<h1>Editing trend</h1>

<%= render 'form' %>

<%= link_to 'Show', @trend %> |
<%= link_to 'Back', trends_path %>

app/views/trends/index.html.erb
<h1>Listing trends</h1>

<table>
  <tr>
    <th>Word</th>
    <th>Excluded</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trends.each do |trend| %>
  <tr>
    <td><%= trend.word %><td>
    <td><%= trend.excluded %><td>

    <td><%= link_to 'Show', trend %></td>
    <td><%= link_to 'Edit', edit_trend_path(trend) %></td>
    <td><%= link_to 'Destroy', trend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/trends/show.html.erb
<p id="notice"><%= notice %></p>

<% @trend.dreams.each do |dream| %>
    <%= link_to dream.name, dream_path(dream) %>
<% end %>

<%= link_to 'Edit', edit_trend_path(@trend) %> |
<%= link_to 'Back', trends_path %>